title: The Carbon Field
author: coded carbon
email: codedcarbonconnect@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning is to knowledge, what carbon is to diamonds. Feel free to join us on this adventure

# social links
twitter_username: CodedCarbon
github_username:  coded-carbon
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
